Working
Hamsterrhino/password-manager pull request #1
Opened 2020-10-06 14:49 UTC by Hamsterrhino

2020-10-07 06:44 UTC, drewxa commented on Password Manager/Password Manager.cpp
> +			std::string sqstring = "INSERT INTO Passwords VALUES('" + arg + "','" + arg1 + "','" + password + "');";
возможна SQL инъекция

2020-10-07 06:44 UTC, drewxa commented on Password Manager/Password Manager.cpp
> +	sqlite3* db = 0; // ����� ������� ���������� � ��
я бы какую-то библиотеку использовал бы для SqlLite

2020-10-07 06:44 UTC, drewxa commented on Password Manager/Password Manager.cpp
> +	// ��������� ����������
кодировку поправить

2020-10-11 20:37 UTC, Alex-Kuz commented
Необходимо убрать миллион бинарей, которые не являются вашим кодом.
Это метафайлы, которые создает VS? Я не знаю, что это, и знать не хочу. В системе контроля версий этого быть не должно.

2020-10-11 20:39 UTC, Alex-Kuz commented
Нэйминг коммитов и ПРов обсудим лично.
Оставляю этот коммент, чтобы самому не забыть.

2020-10-11 20:43 UTC, Alex-Kuz requested changes
Очень тяжело читать: большая часть файлов - мусор, код даже трудно найти.
В самом коде нет комментариев, без чего сложно ориентироваться даже в таких нетрудных для понимания участках.

2020-10-11 20:43 UTC, Alex-Kuz commented on Password Manager/Password Manager.cpp
> +	// ��������� ����������
Или писать только на английском.

2020-10-12 19:23 UTC, Alex-Kuz requested changes
Мусор надо удалить и почистить решение в принципе.

2020-10-12 19:23 UTC, Alex-Kuz commented on Password Manager/Password Manager.cpp
> +			std::string arg1 = argv[3];
Переименовать переменные.

2020-10-12 19:23 UTC, Alex-Kuz commented on Password Manager/Password Manager.cpp
> +			sql = sqstring.c_str();
Смысл переменной?
Это запрос?

2020-10-12 19:23 UTC, Alex-Kuz commented on Password Manager/Password Manager.cpp
> +}
Что эта функция делает? По сигнатуре понять почти нереально.

2020-10-12 19:23 UTC, Alex-Kuz commented on Password Manager/Password Manager.cpp
> +			std::string sqstring = "SELECT * from Passwords WHERE SOURCE = '" + arg +"';";
Та же уязвимость для инъекций.

2020-11-20 08:19 UTC, drewxa requested changes

2020-11-20 08:19 UTC, drewxa commented on Password Manager/Password Manager.cpp
> +        unsigned char *key = new unsigned char[strlen(keystring.c_str()) + 1];
std::vector

2020-11-20 08:19 UTC, drewxa commented on Password Manager/Password Manager.cpp
> +  if (sqlite3_open("my_cosy_database.db", &db))
Серьезно? sqlite3_open возвращает true если ошибка произошла?

2020-11-20 08:19 UTC, drewxa commented on Password Manager/Password Manager.cpp
> +      switch (*argv[1]) {
подключите нормальную библиотеку для работы с аргументами командной строки

2020-11-20 08:19 UTC, drewxa commented on Password Manager/Password Manager.cpp
> +          sqlite3_free(err);
наверное тут ошибка и не надо выполнять код после if ?

2020-11-20 08:19 UTC, drewxa commented on Password Manager/Password Manager.cpp
> +          std::cout << stderr << "������ SQL: " << err << std::endl;
кодировка поехала

2020-11-20 08:19 UTC, drewxa commented on Password Manager/Password Manager.cpp
> +        unsigned char *encryptedpass =
std::vector

2020-11-20 08:19 UTC, drewxa commented on Password Manager/Password Manager.cpp
> +            "('Source','Login','Password') VALUES (@0,@1,@2);";
пробелы после ,

2020-11-20 08:19 UTC, drewxa commented on Password Manager/Password Manager.cpp
> +        sqlite3_close(db);
Я все же либо за:
 * использовать готовую обертку над sqlite3, чтобы не париться с низкоуровневым интерфейсом
 * или написать свою обертку под свои нужды
 * или хотя бы использовать unique_ptr чтобы он автоматом освобождал ресурсы за вами

2020-11-20 08:25 UTC, Hamsterrhino commented on Password Manager/Password Manager.cpp
> +  if (sqlite3_open("my_cosy_database.db", &db))
sqlite3_open сам по себе, открывает базу данных. Если ошибки не нашлось, то он открывает её и идёт дальше. То есть
error=false
Если ошибка есть, то 
error=true
и выполняет алгоритм if.

2020-11-20 08:29 UTC, Hamsterrhino commented on Password Manager/Password Manager.cpp
> +        unsigned char *key = new unsigned char[strlen(keystring.c_str()) + 1];
Вопрос, а надо ли переводить char в вектор? Тогда придёться хранить в векторе по одному char'у, да и алгоритм надо будут переписать чутка, не говоря уже про непредвиденные ошибки.

2020-11-20 08:29 UTC, Hamsterrhino commented on Password Manager/Password Manager.cpp
> +          sqlite3_free(err);
Правда ваша, исправил

2020-11-20 08:29 UTC, Hamsterrhino commented on Password Manager/Password Manager.cpp
> +          std::cout << stderr << "������ SQL: " << err << std::endl;
Исправил

2020-11-20 08:30 UTC, Hamsterrhino commented on Password Manager/Password Manager.cpp
> +        unsigned char *encryptedpass =
Тоже самое что и с key, я из алгоритма получаю unsigned char*, переводить это в вектор уж очень не удобно.

2020-11-20 08:31 UTC, Hamsterrhino commented on Password Manager/Password Manager.cpp
> +            "('Source','Login','Password') VALUES (@0,@1,@2);";
Исправил, вроде.

2020-11-20 08:34 UTC, Hamsterrhino commented on Password Manager/Password Manager.cpp
> +      switch (*argv[1]) {
Порекомендуйте "нормальную" библиотеку тогда? Просто не уверен какую взять? (На примете только boost/program_options)

2020-11-30 21:59 UTC, merged